---
title: "Morphological_Data_MP_MR_2025"
author: "Maxximus Ramsaroop"
date: "2025-04-02"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rstatix)
library(dplyr)
library(Hmisc)
```


```{r, include=FALSE}
f<- "C:/Users/maxma/Downloads/Morphological_Data_MP_MR_2025.csv"

morpho_df<- read_csv(f)

morpho_df <- morpho_df|> mutate(MPbinary = ifelse(Treatment == "Control", 0, 1), Fish_condition_factor = BW_wet/Standard_Length, GSI = (Gonads_wet/BW_wet)*100)

morpho_df<- morpho_df |> rename(Fish_ID = `Fish ID`)

view(morpho_df)

write.csv(morpho_df,"C:/Users/maxma/Downloads/Morphological_Data_MP_MR_2025_r_copy.csv" )
```

```{r Exploratory Analyses: Histograms, Rudimentary Correlations, Etc Chunk 1, message=FALSE, warning=FALSE}

summary(morpho_df) #means & median of each variable

morpho_df |> group_by(Sex, Treatment)|> summarise(n= n()) #number of individuals by treatment and sex

for (col in names(morpho_df)) {
  if (is.numeric(morpho_df[[col]])) {
    hist(morpho_df[[col]], main = paste("Histogram of", col), xlab = col)
  }
} # creates histogram of all numeric data through a for loop


lapply(morpho_df[sapply(morpho_df, is.numeric)], shapiro.test) # shapiro tests all numeric data for normality; gonopodium length is normal, all else non-normal

```

```{r boxplots of morpho variables by sex, message=FALSE, warning=FALSE}
# List of column names you want to plot
variables <- c("Standard_Length", "BW_wet", "Brain_wet", "Gills_wet", "GI_wet", 
               "Gonads_wet", "BW_dry", "gills_Dry", "guts_Dry", "gonads_Dry", 
               "Fish_condition_factor", "GSI")

other_variables<- c("proportional_BW_wet", "proportional_Brain_wet", "proportional_Gills_wet", "proportional_GI_wet", "proportional_Gonads_wet", "proportional_BW_dry", "proportional_gills_Dry", "proportional_guts_Dry", "proportional_gonads_Dry", "proportional_gonopodium_length")

# Loop through and generate boxplots of each base morpho trait by sex
lapply(variables, function(var) {
  boxplot(morpho_df[[var]] ~ morpho_df$Sex,
          main = var,
          ylab = var,
          xlab = "Sex")
})
# most all morpho variables appear to differ by sex. Females appear to have greater weight and standard length than males. Remales appear to have better fish condition factors than males. 
```

```{r boxplot of morpho traits by treatment, message=FALSE, warning=FALSE}
# Loop through and generate boxplots of each base morpho trait by treatment
lapply(variables, function(var) {
  boxplot(morpho_df[[var]] ~ morpho_df$Treatment,
          main = var,
          ylab = var,
          xlab = "Treatment")
})
```

```{r boxplot of morpho traits by sex and treatment, message=FALSE, warning=FALSE}

lapply(variables, function(var) {
  ggplot(mapping = aes(morpho_df$Treatment, morpho_df[[var]], fill = morpho_df$Sex)) + geom_boxplot() + ylab(var)
})

```

```{r Identify Outliers via z score and remove them}
zscore_morpho_df <- morpho_df |>
  mutate(across(where(is.numeric), ~ as.numeric(scale(.)[,1]), .names = "z_{.col}")) # mutate(across()) mutates across all columns
# where(is.numeric) tells across to only work on columns that are numeric
# ~ as.numeric(scale(.)[,1]) tells mutate to mutate a numeric z score  for the columns selected by where(is.numeric())
# .names = "z_{.col}" sets names of the new mutated columns to z_(previous column name) so that it doestn replace the old values

test<- iris |> mutate(across(c(Sepal.Length, Sepal.Width), round, .names = "round_{.col}"))
test

morpho_df_z_score_filtered <- zscore_morpho_df |>
  filter(if_any(starts_with("z_"), ~ ifelse(is.na(.), FALSE, abs(.) > 3.5)) ==FALSE) |> 
    select(-starts_with("z_"))
# if_any() selects any columns that fulfill the requirement in the function
# starts_with() tells if any to only select columns where the string colname starts with "z_"
# ~ takes the previous columns that start with z_ and if any cells contain NA, they are not filtered, else the absolute value of it is taken and if it is greater than 3.5  it ==TRUE and in the filter function it MUST == FALSE to be included. If it is <3.5 it will spit out FALSE ==FALSE and be kept
# select(-starts_with("z_")) then selects all columns that dont start with "z_"

morpho_df_z_score_filtered<- morpho_df_z_score_filtered |> mutate(across((ends_with("_wet")), ~ ./BW_wet, .names = "proportional_{.col}"))

morpho_df_z_score_filtered<- morpho_df_z_score_filtered |> mutate(across((ends_with("_Dry")), ~ ./BW_dry, .names = "proportional_{.col}"))

morpho_df_z_score_filtered<- morpho_df_z_score_filtered |> mutate(proportional_gonopodium_Length = Gonadopodium_Length/Standard_Length)

morpho_df_z_score_filtered

test


view(morpho_df_z_score_filtered)
```


```{r morpho_df_z_score_filtered exploratory analysis, warning=FALSE}


for (col in names(morpho_df_z_score_filtered)) {
  if (is.numeric(morpho_df_z_score_filtered[[col]])) {
    hist(morpho_df_z_score_filtered[[col]], main = paste("Histogram of", col), xlab = col)
  }
} 

lapply(variables, function(var) {
  boxplot(morpho_df_z_score_filtered[[var]] ~ morpho_df_z_score_filtered$Sex,
          main = var,
          ylab = var,
          xlab = "Sex")
})

lapply(variables, function(var) {
  boxplot(morpho_df_z_score_filtered[[var]] ~ morpho_df_z_score_filtered$Treatment,
          main = var,
          ylab = var,
          xlab = "Treatment")
})

lapply(variables, function(var) {
  ggplot(mapping = aes(morpho_df_z_score_filtered$Treatment, morpho_df_z_score_filtered[[var]], fill = morpho_df_z_score_filtered$Sex)) + geom_boxplot() + ylab(var) + geom_jitter()
})


lapply(other_variables, function(var) {
  boxplot(morpho_df_z_score_filtered[[var]] ~ morpho_df_z_score_filtered$Sex,
          main = var,
          ylab = var,
          xlab = "Sex")
})

lapply(other_variables, function(var) {
  boxplot(morpho_df_z_score_filtered[[var]] ~ morpho_df_z_score_filtered$Treatment,
          main = var,
          ylab = var,
          xlab = "Treatment")
})


lapply(other_variables, function(var) {
  ggplot(mapping = aes(morpho_df_z_score_filtered$Treatment, morpho_df_z_score_filtered[[var]], fill = morpho_df_z_score_filtered$Sex)) + geom_boxplot() + ylab(var) + geom_jitter()
})

```



