---
title: "mating behavior data 2025"
author: "Maxximus Ramsaroop"
date: "2025-02-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rstatix)
```

load in mating behavior data for the first time
```{r}
file<- "C:/Users/maxma/Desktop/NumericalEcology/BORIS Mating Behavior r data 2.csv"
matingbehaviordf<- read_csv(file = file)

matingbehaviordf <- matingbehaviordf |> mutate(approachbOPS = `approach from behind Number of occurrences`/Total_assay_length, approachfsOPS = `approach from front or side Number of occurrences`/Total_assay_length, chaseOPS = `chase Number of occurrences`/Total_assay_length, strikeOPS = `strike Number of occurrences`/Total_assay_length, tailingOPS= `tailing Number of occurrences`/Total_assay_length, MPbinary = if_else(Treatment == "C", 0, 1))

matingbehaviordf<- matingbehaviordf|> rename(approach_from_behind_Occurences = `approach from behind Number of occurrences`, approach_from_front_or_side_Occurences = `approach from front or side Number of occurrences`, chase_Occurences = `chase Number of occurrences`, strike_Occurences = `strike Number of occurrences`, tailing_Occurences = `tailing Number of occurrences`, tailing_totalDuration = `tailing Total duration`, tailing_meanDuration = `tailing Duration mean`, tailing_Proportion_of_total_Time = `tailing Proportion of time`, tailing_stdevDuration = `tailing Duration std dev`, Total_video_length = `Total video length (s)`)


write.csv(matingbehaviordf, "C:/Users/maxma/Desktop/MP or Pollution Project/BORIS Mating Behavior r data.csv", )

file<- "C:/Users/maxma/Desktop/MP or Pollution Project/BORIS Mating Behavior r data.csv"
matingbehaviordf<- read_csv(file = file)
matingbehaviordf<- matingbehaviordf |> select(!1)
```


```{r histograms of variables, message = FALSE, warning=FALSE}

mating_variables<- c("strike_Occurences", "approach_from_behind_Occurences","approach_from_front_or_side_Occurences","chase_Occurences","strike_Occurences", "tailing_Occurences", "tailing_totalDuration")

lapply(mating_variables, function(var) { #lapply function applies a function to a list of elements; in this case the list is mating variables and the function is var()
  hist(matingbehaviordf[[var]], main = paste("Histogram of", var), xlab= var)
})
```

```{r boxplots variables by treatment, message=FALSE, warning=FALSE}
lapply(mating_variables, function(var) {
  boxplot(matingbehaviordf[[var]] ~ matingbehaviordf$Treatment,
          main = var,
          ylab = var,
          xlab = "Treatment")
})
```

```{r boxplots variables by mpbinary, message=FALSE, warning=FALSE}
lapply(mating_variables, function(var) {
  boxplot(matingbehaviordf[[var]] ~ matingbehaviordf$MPbinary,
          main = var,
          ylab = var,
          xlab = "MPbinary")
})
```



```{r figure for student's poster}
chase_occurences_anovaplot_bytreatment<- ggplot(matingbehaviordf, mapping = aes(Treatment, chase_Occurences, fill = Treatment)) + geom_boxplot(width = 0.75) + geom_jitter() + theme_bw() +
  scale_x_discrete(name = " ", labels = c("C" = "Control", "L" = "Low", "H" = "High"))

chase_occurences_anovaplot_bytreatment

matingbehaviordf$Treatment <- factor(matingbehaviordf$Treatment, levels = c("C", "L", "H"))
treatment_colors <- c(
  "C" = "#ff218c",
  "L" = "#ffd800",
  "H" = "#21b1ff"
)

ggplot(matingbehaviordf, mapping = aes(Treatment, strike_Occurences/600, fill = Treatment)) + geom_boxplot(width = 0.75) + geom_jitter() + theme_bw() +
  scale_x_discrete(name = " ", labels = c("C" = "Control", "L" = "Low", "H" = "High")) + 
  scale_fill_manual(values= treatment_colors) + theme_bw()

```

```{r}
iqr_na <- function(v, threshold = 3.0) {
  if (!is.numeric(v)) return(v)  # Leave non-numeric columns untouched
  
  v_clean <- v[!is.na(v)]
  Q1 <- quantile(v_clean, 0.25, na.rm = TRUE)
  Q3 <- quantile(v_clean, 0.75, na.rm = TRUE)
  IQR_val <- Q3 - Q1
  
  lower_bound <- Q1 - threshold * IQR_val
  upper_bound <- Q3 + threshold * IQR_val
  
  # Replace outliers with NA
  v[v < lower_bound | v > upper_bound] <- NA
  return(v)
}

# Apply to all numeric columns in your dataframe

for (col in names(matingbehaviordf)) {
  if (is.numeric(matingbehaviordf[[col]])) {
    matingbehaviordf[[col]] <- iqr_na(matingbehaviordf[[col]], threshold = 3.0)
  }
}

```




```{r ANOVAS & Kruskals}
aov1<- aov(matingbehaviordf$strikeOPS ~ matingbehaviordf$Treatment + matingbehaviordf$MPbinary)
summary(aov1)

matingbehaviordf|> kruskal_test(strike_Occurences ~ Treatment)
matingbehaviordf|> kruskal_test(tailing_Occurences ~ Treatment)
matingbehaviordf|> kruskal_test(chase_Occurences ~ Treatment)
matingbehaviordf|> kruskal_test(approach_from_behind_Occurences ~ Treatment)
matingbehaviordf|> kruskal_test(approach_from_front_or_side_Occurences ~ Treatment)

summary(aov(matingbehaviordf$Sexual_Behavior_Frequency ~ matingbehaviordf$MPbinary))

boxplot(matingbehaviordf$Sexual_Behavior_Frequency ~ matingbehaviordf$Treatment)

```


```{r bind morphological data to mating behavior}
morphofile<- "C:/Users/maxma/Desktop/MP or Pollution Project/morpho data 1-31-25.csv"
morphologydf<- read_csv(morphofile, col_names = T)

morphologydf<- subset(morphologydf, !is.na(`Fish ID`))

morphologydf[morphologydf== "-"] <- NA

morphologydf |> count(`Fish ID`) |> filter(n>1)

morphologydf<- filter(morphologydf, !morphologydf$`Fish ID` == "6LF-Bee" | !morphologydf$`Fish ID`== "6LM-Anchovy")

morphologydf<- morphologydf |> rename(FishID = `Fish ID`)

male_morphology_df<- filter(morphologydf, Sex == "Male")

morphology_matingbehavior_merged<- merge(matingbehaviordf, morphologydf, by = "FishID")

morphologydf

morphology_matingbehavior_merged
matingbehaviordf

malemerge<- merge(male_morphology_df, matingbehaviordf, by = "FishID")

malemerge


scoto_detour<- merge(scoto_df, detourdf, by = "Fish_ID")

view(scoto_detour)

```






